/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolsIndexRouteImport } from './routes/pools/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PoolsLaborRouteImport } from './routes/pools/labor'
import { Route as PoolsEquipmentRouteImport } from './routes/pools/equipment'
import { Route as EstimateEstimateIdRouteImport } from './routes/estimate/$estimateId'
import { Route as EstimateEstimateIdIndexRouteImport } from './routes/estimate/$estimateId.index'
import { Route as AdminMemberMemberIdRouteImport } from './routes/admin/member.$memberId'
import { Route as EstimateEstimateIdWbsWbsIdRouteImport } from './routes/estimate/$estimateId.wbs.$wbsId'
import { Route as EstimateEstimateIdPhasePhaseIdRouteImport } from './routes/estimate/$estimateId.phase.$phaseId'

const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsIndexRoute = PoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PoolsLaborRoute = PoolsLaborRouteImport.update({
  id: '/pools/labor',
  path: '/pools/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsEquipmentRoute = PoolsEquipmentRouteImport.update({
  id: '/pools/equipment',
  path: '/pools/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateEstimateIdRoute = EstimateEstimateIdRouteImport.update({
  id: '/estimate/$estimateId',
  path: '/estimate/$estimateId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateEstimateIdIndexRoute = EstimateEstimateIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstimateEstimateIdRoute,
} as any)
const AdminMemberMemberIdRoute = AdminMemberMemberIdRouteImport.update({
  id: '/member/$memberId',
  path: '/member/$memberId',
  getParentRoute: () => AdminRoute,
} as any)
const EstimateEstimateIdWbsWbsIdRoute =
  EstimateEstimateIdWbsWbsIdRouteImport.update({
    id: '/wbs/$wbsId',
    path: '/wbs/$wbsId',
    getParentRoute: () => EstimateEstimateIdRoute,
  } as any)
const EstimateEstimateIdPhasePhaseIdRoute =
  EstimateEstimateIdPhasePhaseIdRouteImport.update({
    id: '/phase/$phaseId',
    path: '/phase/$phaseId',
    getParentRoute: () => EstimateEstimateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/estimates': typeof EstimatesRoute
  '/estimate/$estimateId': typeof EstimateEstimateIdRouteWithChildren
  '/pools/equipment': typeof PoolsEquipmentRoute
  '/pools/labor': typeof PoolsLaborRoute
  '/admin/': typeof AdminIndexRoute
  '/pools/': typeof PoolsIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/estimate/$estimateId/': typeof EstimateEstimateIdIndexRoute
  '/estimate/$estimateId/phase/$phaseId': typeof EstimateEstimateIdPhasePhaseIdRoute
  '/estimate/$estimateId/wbs/$wbsId': typeof EstimateEstimateIdWbsWbsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estimates': typeof EstimatesRoute
  '/pools/equipment': typeof PoolsEquipmentRoute
  '/pools/labor': typeof PoolsLaborRoute
  '/admin': typeof AdminIndexRoute
  '/pools': typeof PoolsIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/estimate/$estimateId': typeof EstimateEstimateIdIndexRoute
  '/estimate/$estimateId/phase/$phaseId': typeof EstimateEstimateIdPhasePhaseIdRoute
  '/estimate/$estimateId/wbs/$wbsId': typeof EstimateEstimateIdWbsWbsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/estimates': typeof EstimatesRoute
  '/estimate/$estimateId': typeof EstimateEstimateIdRouteWithChildren
  '/pools/equipment': typeof PoolsEquipmentRoute
  '/pools/labor': typeof PoolsLaborRoute
  '/admin/': typeof AdminIndexRoute
  '/pools/': typeof PoolsIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/estimate/$estimateId/': typeof EstimateEstimateIdIndexRoute
  '/estimate/$estimateId/phase/$phaseId': typeof EstimateEstimateIdPhasePhaseIdRoute
  '/estimate/$estimateId/wbs/$wbsId': typeof EstimateEstimateIdWbsWbsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/estimates'
    | '/estimate/$estimateId'
    | '/pools/equipment'
    | '/pools/labor'
    | '/admin/'
    | '/pools/'
    | '/admin/member/$memberId'
    | '/estimate/$estimateId/'
    | '/estimate/$estimateId/phase/$phaseId'
    | '/estimate/$estimateId/wbs/$wbsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estimates'
    | '/pools/equipment'
    | '/pools/labor'
    | '/admin'
    | '/pools'
    | '/admin/member/$memberId'
    | '/estimate/$estimateId'
    | '/estimate/$estimateId/phase/$phaseId'
    | '/estimate/$estimateId/wbs/$wbsId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/estimates'
    | '/estimate/$estimateId'
    | '/pools/equipment'
    | '/pools/labor'
    | '/admin/'
    | '/pools/'
    | '/admin/member/$memberId'
    | '/estimate/$estimateId/'
    | '/estimate/$estimateId/phase/$phaseId'
    | '/estimate/$estimateId/wbs/$wbsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EstimatesRoute: typeof EstimatesRoute
  EstimateEstimateIdRoute: typeof EstimateEstimateIdRouteWithChildren
  PoolsEquipmentRoute: typeof PoolsEquipmentRoute
  PoolsLaborRoute: typeof PoolsLaborRoute
  PoolsIndexRoute: typeof PoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/': {
      id: '/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof PoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pools/labor': {
      id: '/pools/labor'
      path: '/pools/labor'
      fullPath: '/pools/labor'
      preLoaderRoute: typeof PoolsLaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/equipment': {
      id: '/pools/equipment'
      path: '/pools/equipment'
      fullPath: '/pools/equipment'
      preLoaderRoute: typeof PoolsEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/$estimateId': {
      id: '/estimate/$estimateId'
      path: '/estimate/$estimateId'
      fullPath: '/estimate/$estimateId'
      preLoaderRoute: typeof EstimateEstimateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/$estimateId/': {
      id: '/estimate/$estimateId/'
      path: '/'
      fullPath: '/estimate/$estimateId/'
      preLoaderRoute: typeof EstimateEstimateIdIndexRouteImport
      parentRoute: typeof EstimateEstimateIdRoute
    }
    '/admin/member/$memberId': {
      id: '/admin/member/$memberId'
      path: '/member/$memberId'
      fullPath: '/admin/member/$memberId'
      preLoaderRoute: typeof AdminMemberMemberIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/estimate/$estimateId/wbs/$wbsId': {
      id: '/estimate/$estimateId/wbs/$wbsId'
      path: '/wbs/$wbsId'
      fullPath: '/estimate/$estimateId/wbs/$wbsId'
      preLoaderRoute: typeof EstimateEstimateIdWbsWbsIdRouteImport
      parentRoute: typeof EstimateEstimateIdRoute
    }
    '/estimate/$estimateId/phase/$phaseId': {
      id: '/estimate/$estimateId/phase/$phaseId'
      path: '/phase/$phaseId'
      fullPath: '/estimate/$estimateId/phase/$phaseId'
      preLoaderRoute: typeof EstimateEstimateIdPhasePhaseIdRouteImport
      parentRoute: typeof EstimateEstimateIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMemberMemberIdRoute: typeof AdminMemberMemberIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminMemberMemberIdRoute: AdminMemberMemberIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EstimateEstimateIdRouteChildren {
  EstimateEstimateIdIndexRoute: typeof EstimateEstimateIdIndexRoute
  EstimateEstimateIdPhasePhaseIdRoute: typeof EstimateEstimateIdPhasePhaseIdRoute
  EstimateEstimateIdWbsWbsIdRoute: typeof EstimateEstimateIdWbsWbsIdRoute
}

const EstimateEstimateIdRouteChildren: EstimateEstimateIdRouteChildren = {
  EstimateEstimateIdIndexRoute: EstimateEstimateIdIndexRoute,
  EstimateEstimateIdPhasePhaseIdRoute: EstimateEstimateIdPhasePhaseIdRoute,
  EstimateEstimateIdWbsWbsIdRoute: EstimateEstimateIdWbsWbsIdRoute,
}

const EstimateEstimateIdRouteWithChildren =
  EstimateEstimateIdRoute._addFileChildren(EstimateEstimateIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EstimatesRoute: EstimatesRoute,
  EstimateEstimateIdRoute: EstimateEstimateIdRouteWithChildren,
  PoolsEquipmentRoute: PoolsEquipmentRoute,
  PoolsLaborRoute: PoolsLaborRoute,
  PoolsIndexRoute: PoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
