import { config } from "@truss/eslint-config/react-internal";

/**
 * ESLint config for the Precision desktop app.
 *
 * WHY `react-internal` rather than `next-js`: Precision is a Vite + Tauri app.
 * It shares the React/hooks rules with the internal packages, not Next's.
 */
export default [
  {
    ignores: [
      "dist/**",
      "src-tauri/target/**",
      // Generated by @tanstack/router-plugin on every dev/build.
      "src/routeTree.gen.ts",
    ],
  },
  ...config,
];
