/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as AdminMemberMemberIdRouteImport } from './routes/admin/member.$memberId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId.index'
import { Route as ProjectProjectIdReportsRouteImport } from './routes/project/$projectId.reports'
import { Route as ProjectProjectIdSettingsRouteImport } from './routes/project/$projectId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMemberMemberIdRoute = AdminMemberMemberIdRouteImport.update({
  id: '/member/$memberId',
  path: '/member/$memberId',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdReportsRoute = ProjectProjectIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/project/$projectId/reports': typeof ProjectProjectIdReportsRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/project/$projectId/reports': typeof ProjectProjectIdReportsRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/member/$memberId': typeof AdminMemberMemberIdRoute
  '/project/$projectId/reports': typeof ProjectProjectIdReportsRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/projects'
    | '/project/$projectId'
    | '/admin/'
    | '/admin/member/$memberId'
    | '/project/$projectId/reports'
    | '/project/$projectId/settings'
    | '/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/admin'
    | '/admin/member/$memberId'
    | '/project/$projectId/reports'
    | '/project/$projectId/settings'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/projects'
    | '/project/$projectId'
    | '/admin/'
    | '/admin/member/$memberId'
    | '/project/$projectId/reports'
    | '/project/$projectId/settings'
    | '/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/member/$memberId': {
      id: '/admin/member/$memberId'
      path: '/member/$memberId'
      fullPath: '/admin/member/$memberId'
      preLoaderRoute: typeof AdminMemberMemberIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/reports': {
      id: '/project/$projectId/reports'
      path: '/reports'
      fullPath: '/project/$projectId/reports'
      preLoaderRoute: typeof ProjectProjectIdReportsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings': {
      id: '/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMemberMemberIdRoute: typeof AdminMemberMemberIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminMemberMemberIdRoute: AdminMemberMemberIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdReportsRoute: typeof ProjectProjectIdReportsRoute
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdReportsRoute: ProjectProjectIdReportsRoute,
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
